import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import Hero from "@/components/Hero/Hero";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Coding Jojo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">

            <Navbar />
            
{/* <Hero /> */}
            {children}
            <Footer />
        </div>
      </body>
    </html>
  );
}
